

import Aside from "@/components/Aside";
import Header from "@/components/Header";

export const metadata = {
    title: 'Student',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
                    <>
                        <div className={"flex flex-row w-full"}>
                            <div className={"aside"}>

                                <Aside/>


                            </div>
                            <div className={"flex flex-col w-full "}>
                                <Header/>
                                <div className={"h-[calc(100vh-60px)] overflow-auto"}>
                                    {children}
                                </div>
                            </div>
                        </div>
                    </>
    )
}
